configs:
  output_bucket: "s3://bolt_pipeliner/tables/"
  flatfile_bucket: "s3://bolt_pipeliner/flatfiles/"
  schema: bolt_pipeliner
  catalog: catalog

layers:
  flatfile: etl/_flatfile
  bronze: etl/0_bronze
  silver: etl/1_silver
  gold: etl/2_gold

flatfile:
  - module: flatfile_storm_events
    description: "Storm events from recorded from ncei.noaa.gov"
    class_name: ETLBase
    input_tables:
      storm_events: "storm_events.csv"
    output_table_name: storm_events

  - module: flatfile_cpi_regional
    description: "CPI regional files pulled from https://url.us.m.mimecastprotect.com/s/Q9ZbCjRny7tGRMZlWf5iZtme6Em"
    class_name: ETLBase
    input_tables:
      flat: "reshaped_CPI_Regional.csv"
    output_table_name: cpi_regional

  - module: flatfile_gas_prices
    description: "Gas prices pulled from https://url.us.m.mimecastprotect.com/s/L65RCkRoz9tX56oYxF9srtGHHSH/"
    class_name: ETLBase
    input_tables:
      flat: "reshaped_Gas_Prices.csv"
    output_table_name: gas_prices

  - module: flatfile_digital_session_transaction_raw
    description: "Digital Transactions by section."
    class_name: ETLBase
    input_tables:
      flat: "digital_session_transaction_raw.parquet"
    output_table_name: digital_session_transaction_raw

bronze: []

silver:
  - module: silver_fct_state_gas_cpi_monthly
    description: "Monthly CPI, gas price, and inflation metrics with 12-month rolling averages and percent changes, by state."
    incremental: true
    class_name: ETLBase
    input_tables:
      cpi: flatfile_cpi_regional
      gas: flatfile_gas_prices
    output_table_name: fct_state_gas_cpi_monthly
    partition_by:
      - year_month
    tests:
      - not_null:  [year_month, state]
      - unique:    [year_month, state]
      - row_count: { min: 1 }
      - freshness: { column: year_month, max_age_days: 90 }

gold: []